feat: Удалил тестовую страницу. Удалил пробную навигацию. Переместил …
kseniakap/trafalgar pull request #18
Opened 2024-06-25 15:34 UTC by Kalabass

… меню на главную

2024-06-26 06:41 UTC, al-revenko commented on src/layouts/Default.tsx
Почему дропнул? Не уверен, но это же вроде как не тестовый компонент

2024-06-27 12:42 UTC, Kalabass commented on src/layouts/Default.tsx
"удалить пробную навигацию " https://ru.yougile.com/team/d0330940e9c6/Trafalgar#TRA-22
в лейауте кроме тестовой навигации ничего не было

2024-06-27 12:51 UTC, Kalabass commented on src/layouts/Default.tsx
А, там видимо описание видно только исполнителю

2024-06-27 13:01 UTC, aidagalimova commented on src/layouts/Default.tsx
в layout обернуты все страницы, но не знаю нужен ли он

2024-06-27 13:31 UTC, al-revenko commented on src/layouts/Default.tsx
ну так как мы все не шарим я кину апрув)))

2024-06-27 13:31 UTC, al-revenko approved these changes

2024-06-27 13:47 UTC, aidagalimova approved these changes

2024-06-27 14:04 UTC, sspopkov requested changes
DefaultLayout не трогаем, в данном проекте его не используем по назначению, но по структуре проекта он обязательно должен быть

2024-06-27 14:38 UTC, sspopkov requested changes
![image](https://github.com/kseniakap/trafalgar/assets/52671474/42fa59ed-a16c-439e-a5e4-cb6efe872286)
Хедер уехал на мобильных устройствах

2024-06-27 15:07 UTC, sspopkov approved these changes
Ошибка вёрстки пофикшена в другой ветке

2024-06-27 15:07 UTC, merged