Feature/traf 4
kseniakap/trafalgar pull request #19
Opened 2024-06-25 21:54 UTC by Kalabass

2024-06-26 07:17 UTC, al-revenko requested changes
C кодом вроде всё норм. А с вёрсткой есть небольшие проблемы 

В менюшке есть горизонтальный скролл.  Можешь сделать переход на мобильное меню с 1024px (iPad) - это отчасти поможет 
![Снимок](https://github.com/kseniakap/trafalgar/assets/73707133/ca0fa674-76a2-4dd1-9688-b20b0072aba0)
![Снимок1](https://github.com/kseniakap/trafalgar/assets/73707133/dca1cb13-8bde-4ac9-94d7-0184078e9ffc)

В мобильном меню поиск немного не соответствует макету и по-хорошему кнопки (ссылки) надо заменить на теги `<a>` вместо `<p>` + навесить стили на фокус этих ссылок 

![2024-06-26_13-51-56](https://github.com/kseniakap/trafalgar/assets/73707133/eb5563f9-36a6-45ce-a559-aef30ed891f3)

2024-06-26 10:11 UTC, G00syara approved these changes, later dismissed

2024-06-26 15:19 UTC, kseniakap approved these changes
1) Стили по ширине менюшки для мобилки не применились, забыл прописать px (компонет DrawerList)
`const DrawerContainer = styled(Box)`
  width: 256;
` 
2) Не соответствует макету для мобилки (стоит подправить лого, изменить цвет у менюшки, там темно-синий, а не черный) 
![image](https://github.com/kseniakap/trafalgar/assets/119811424/ec639b36-f378-420b-8ffc-dd8a8ac2e181)
3) Поле поиска не соответствует макету (видела, что ты создавал свой компонент SearchTextField, но в проекте уже есть готовый компонет Input) 
![image](https://github.com/kseniakap/trafalgar/assets/119811424/797f747a-4fab-46a6-8f7a-baf2a293a561)

2024-06-27 13:30 UTC, al-revenko requested changes
По вёрстке всё норм, кроме того что меню всё равно переполняется 

![1 (2)](https://github.com/kseniakap/trafalgar/assets/73707133/746aed14-1bd3-4706-818e-efa38a8408f4)

Смотри как бы я сделал. Убрал бы padding у кнопок в ноль, навесил бы 100% ширины flex контейнера в котором находятся эти кнопки, убрал бы фиксированный gap у него и вкинул на этот контейнер justify-content: space-between; . Не очень красиво, но так зато нет переполнения. Чтобы со стилями кнопок не париться можешь сделать их просто ссылками как в мобильном меню, так будет правильнее.

![Снимок!](https://github.com/kseniakap/trafalgar/assets/73707133/49b74d58-9607-4579-a07e-4bfead38710e)

А дальше я бы сделал так, чтобы мобильное меню появлялось после 1024px . В AppMenu можно просто поменять строчку на эту:
`const isMobile = useMediaQuery(theme.breakpoints.down('iPad'));`

2024-06-27 13:46 UTC, aidagalimova commented
Наверное, не критично, но когда скроллишь, меню верхнее в начале дрыгается. Возможно можно было использовать IntersectionObserver, но это не точно) 
как то так
```
const FullMenu: FC = () => {
  const [isIntersecting, setIsIntersecting] = useState(false);
  const ref = useRef(null);
  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => {
      setIsIntersecting(entry.isIntersecting);
    });
    if (ref) {
      observer.observe(ref.current);
    }
  }, []);
  return (
    <>
      <Wrapper ref={ref} />
      {isIntersecting ? (
        <>
          <TopMenu />
          <MiddleMenu /> <BottomMenu />
        </>
      ) : (
        <ScrollMenu />
      )}
    </>
  );
};

const Wrapper = styled.div`
  position: absolute;
  top: 0%;
  height: 20px;
`;
export default FullMenu;
```

2024-06-27 16:56 UTC, al-revenko approved these changes

2024-06-27 17:07 UTC, sspopkov requested changes
Комментарий Аиды с IntersectionObserver поддерживаю

2024-06-28 10:34 UTC, aidagalimova approved these changes

2024-06-28 12:00 UTC, sspopkov commented on src/components/menu/DesktopMenus/index.tsx
> +  z-index: 1000;
Не используем такие большие величины

2024-06-28 12:00 UTC, sspopkov commented on src/components/menu/DesktopMenus/index.tsx
> +export default DeskTopMenus;
Desktop

2024-06-28 12:30 UTC, Kalabass commented on src/components/menu/DesktopMenus/index.tsx
> +  z-index: 1000;
поменял

2024-06-28 12:30 UTC, Kalabass commented on src/components/menu/DesktopMenus/index.tsx
> +export default DeskTopMenus;
исправил

2024-06-28 12:43 UTC, sspopkov approved these changes

2024-06-28 12:43 UTC, merged