feat(TRA-19): Создание блока Вопросы
kseniakap/trafalgar pull request #20
Opened 2024-06-26 14:24 UTC by kseniakap

2024-06-26 15:01 UTC, aidagalimova commented on src/components/ui/QuestionsBlock/QuestionsBlock.tsx
> +  const handleExpansion = (index: number) => {
для открытия/закрытия вопроса, наверное, можно просто создать отдельный компонент для карточки с вопросом, и регулировать его открытость/закрытость внутри этого компонента
` const [isOpen, setIsOpen] = useState(false);`
`   const handleClick = () => {`
`     setIsOpen(!isOpen);`
`  };`
`  return (`
`    <DropCard onClick={(handleClick)}>`
`      {....}`
`    </DropCard>`
`  );`

2024-06-26 15:04 UTC, aidagalimova commented on src/components/ui/QuestionsBlock/QuestionsBlock.tsx
> +  const renterAllQuestion = (questions: IAllQuestion[]) => {
renter - очепятка?)

2024-06-26 15:07 UTC, aidagalimova commented on src/components/ui/QuestionsBlock/QuestionsBlock.tsx
> +  'position': 'relative',
у стилей есть порядок https://netology-university.bitbucket.io/codestyle/css/#order

2024-06-26 21:34 UTC, aidagalimova approved these changes

2024-06-27 04:23 UTC, al-revenko requested changes

2024-06-27 04:23 UTC, al-revenko commented on src/components/ui/QuestionsBlock/Question.tsx
> +        <AnswerTypography>{answer}</AnswerTypography>
Вместо Typography просто используй стилизованный тег с классом шрифта из assets/style/main.scss. Typography не используй чтобы не переопределять дефолтные стили из mui

2024-06-27 04:23 UTC, al-revenko commented on src/components/ui/QuestionsBlock/Question.tsx
> +}));
При 1440px аккордеон имеет ширину 828px, а по макету должен иметь 900px

2024-06-27 04:23 UTC, al-revenko commented on src/components/ui/QuestionsBlock/Question.tsx
> +}));
Как и писал выше - используй готовые шрифты из main.scss. Пример - шрифты в AnswerTypography немного не по макету, вроде как исправить это можно используя селектор .body-m

2024-06-27 04:23 UTC, al-revenko commented on src/assets/images/decorBlockQuestions.png
Все картинки храним в assets/img . Эту перемести, а auth.png, в рамках этого пр лучше оставь на месте

2024-06-27 15:33 UTC, al-revenko approved these changes

2024-06-27 19:51 UTC, sspopkov approved these changes

2024-06-28 10:32 UTC, Kalabass approved these changes

2024-06-28 10:38 UTC, merged