feat(TRA-18): сверстал блок "Знания"
kseniakap/trafalgar pull request #23
Opened 2024-06-27 07:23 UTC by al-revenko

2024-06-27 09:04 UTC, aidagalimova approved these changes

2024-06-27 12:45 UTC, Kalabass approved these changes

2024-06-27 17:30 UTC, kseniakap approved these changes
Нет адаптации для больших устройств
![image](https://github.com/kseniakap/trafalgar/assets/119811424/7458019a-51bf-429f-a1bc-95e77590b4c8)
Появляется скролл при 393px и 394px

2024-06-27 17:30 UTC, kseniakap commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +          <li key={idx}>
Небольшое предложение, использовать деструкторизацию:
`   {cardsData.map((data, idx) => {
          const { value, title, iconAlt, icon } = data;
          return (
            <li key={idx}>
              ...
            </li>
          );
        })}`

2024-06-27 17:30 UTC, kseniakap commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +            <Button
У кнопок не указал size, по макету font-size: 20px, у тебя 16px, для мобилки 14px

2024-06-27 17:30 UTC, kseniakap commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +  padding-bottom: ${({ theme }) => theme.spacing(6)};
Внешний отступ

2024-06-27 17:30 UTC, kseniakap commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +    padding-bottom: ${({ theme }) => theme.spacing(1)};
Там внешний отступ (стоит использовать margin-bottom, вместо padding-bottom)

2024-06-27 17:30 UTC, kseniakap commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +    padding-bottom: ${({ theme }) => theme.spacing(6)};
Такая же ситуация)

2024-06-28 06:10 UTC, al-revenko commented
> Нет адаптации для больших устройств ![image](https://private-user-images.githubusercontent.com/119811424/343882138-7458019a-51bf-429f-a1bc-95e77590b4c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTI0MjAsIm5iZiI6MTcxOTU1MjEyMCwicGF0aCI6Ii8xMTk4MTE0MjQvMzQzODgyMTM4LTc0NTgwMTlhLTUxYmYtNDI5Zi1hMWJjLTk1ZTc3NTkwYjRjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOFQwNTIyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZThhN2JhMjRmZjkxMGQxMTEyNDBhNzNjYTFlM2I1YTU0YTE1MDg0ZWQzMmJkNTZmYzIxNjQ4Y2NmZjJhYzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O51iXHP6DYLnT8wr6jX3vwJ9FwVfxY-fPsr97neQHAs) Появляется скролл при 393px и 394px

Я не сразу понял про какой ты скролл говоришь. Короч там горизонтальный скролл появляется так как вертикальный скролл выталкивает элементы в бок и они переполняются.

![2024-06-28_12-30-58](https://github.com/kseniakap/trafalgar/assets/73707133/118013b4-93f0-4345-b09f-91e98fc495ff)
На мобилках вертикального скролла нет, поэтому там всё норм будет

![2024-06-28_12-31-55](https://github.com/kseniakap/trafalgar/assets/73707133/cd3851eb-dd1c-48ab-bbc6-83c395eedcd0)

По поводу адаптации для широких экранов - ну она ващета есть)

Я ограничиваю макс. ширину контейнера с контентом до 1440px. Делается это для того, чтобы на широких экранах элементы далеко не разъезжались и пользователи не заработали себе косоглазие.
Наверное можно было бы сделать ширину больше, но у нас макс. ширина макета = 1440px и макетов для более широких экранов нет. Поэтому 1440px я взял как макс. ширину для всего контента. 

Другие мои компоненты также ограничивают свой контент. Нормальная практика кст, гитхаб  и многие другие сайты также делают.

![2024-06-28_12-37-06](https://github.com/kseniakap/trafalgar/assets/73707133/664ab6d7-2d7d-44d4-8581-a2c42a5996a1)

2024-06-28 06:18 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +          <li key={idx}>
Так стрелочная функция немного усложнится, я поэтому и не стал так делать 
![2024-06-28_13-16-52](https://github.com/kseniakap/trafalgar/assets/73707133/8b904f28-d582-4980-8693-09df01be66b6)

2024-06-28 06:30 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +  padding-bottom: ${({ theme }) => theme.spacing(6)};
А какая разница?)  
Я знаю разницу между внешними и внутренними отступами, но мне кажется условным дизайнеру, заказчику кристально, нет, рубиново всё равно как я делаю отступы - лишь бы эти отступы соответствовали макету, а какой тип у этих отступов по моему ваще не важно

2024-06-28 06:30 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +    padding-bottom: ${({ theme }) => theme.spacing(1)};
ну я отписал выше

2024-06-28 06:31 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +    padding-bottom: ${({ theme }) => theme.spacing(6)};
и тут отпишу что отписал выше

2024-06-28 06:37 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +            <Button
это правда, исправлю

2024-06-28 11:46 UTC, G00syara commented
Блок со знаниями для широкого экрана надо увеличить. 
В первую очередь под все остальные реализованные блоки, потому что иначе получается, что у тебя супер маленький блок, по сравнению с другими 
![image](https://github.com/kseniakap/trafalgar/assets/95299564/32fcc428-48ca-4f03-a077-aab3f229df27)
Во вторую очередь никто не просит его растягивать на весь экран, ради косоглазия, можно сделать отступы слева и справа, как на блоке выше и увеличить сам блок в размерах, в высоту и ширину, чтобы не казалось, что он растянут, а хорошо и спокойненько вписывалось, например увеличить вот так
![image](https://github.com/kseniakap/trafalgar/assets/95299564/1253b1c6-54a6-45f2-826a-bc14f5b6a843)

2024-06-28 11:54 UTC, G00syara commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +  padding-bottom: ${({ theme }) => theme.spacing(6)};
Имхо лучше `margin`, потому что `padding` ты отодвигаешь внутренние элементы от границ его блока, а за счёт `margin`, делаешь отступ блока от других блоков, т.к. у тебя кнопки, каждая из который представляет собой не внутренние элементы а целый блок, то лучше использовать `margin`

2024-06-28 12:10 UTC, G00syara requested changes

2024-06-28 12:10 UTC, G00syara commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +  const [isDocCategoryState, setIsDocCategoryState] = useState<boolean>(true);
Тип не обязательно он сам понимает

2024-06-28 12:10 UTC, G00syara commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +    <>
Фрагмент не нужен, у тебя всё итак обёрнуто в `Block`

2024-06-28 12:10 UTC, G00syara commented on src/components/ui/KnowledgeBlock/statCardData.ts
> +export interface IStatCardData {
Интерфейсы без приписки `I` писать, на C# и C++, это норма, на внутреннем проекте, на который вас закинут пишут без него, так что лучше приучаться сразу

2024-06-28 12:10 UTC, G00syara commented on src/types/styled.d.ts
Зачем создавалась `d.ts`? Я найти не могу для чего она, у меня ничего не сломалось по типам когда я удалил её

2024-06-28 12:10 UTC, G00syara commented on src/uttils/toCompactNum.ts
Опечатался в названии папки

2024-06-28 12:10 UTC, G00syara commented on src/uttils/toCompactNum.ts
Также если это `utils` папка, то лучше сразу писать `export function ...`, т.к. ты оттуда будешь экспортировать функции. И почему не через стрелочную сделал?

2024-06-28 12:56 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +  const [isDocCategoryState, setIsDocCategoryState] = useState<boolean>(true);
Ну я понимаю что она сама понимает. Это больше для явной типизации

2024-06-28 13:06 UTC, al-revenko commented on src/types/styled.d.ts
Конечно всё работает - у темы которую провайдит styled-components изначально тип any. Я привёл её к такому же типу как и у темы которую провайдит mui.  

https://styled-components.com/docs/api#create-a-declarations-file

2024-06-28 13:11 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/statCardData.ts
> +export interface IStatCardData {
Ок

2024-06-28 13:16 UTC, al-revenko commented on src/uttils/toCompactNum.ts
Захотел утилиту через функцию сделать 🗿.  Был бы документ по стилю следовал бы ему, а так сделал как посчитал нужным 

исправлю

2024-06-28 13:17 UTC, al-revenko commented on src/components/ui/KnowledgeBlock/KnowledgeBlock.tsx
> +    <>
хорошо

2024-06-28 15:30 UTC, G00syara commented on src/uttils/toCompactNum.ts
По стрелочной просто вопрос)

2024-06-28 15:31 UTC, G00syara commented on src/types/styled.d.ts
Вот это респект

2024-06-29 16:08 UTC, closed without merging