feat(TRA-20): добавила блок "Цены"
kseniakap/trafalgar pull request #24
Opened 2024-06-27 11:52 UTC by aidagalimova

2024-06-27 15:55 UTC, al-revenko commented on src/components/ui/Prices/Prices.tsx
> +  ));
Функция называется pricesList а рендерит она только айтемы списка. Наверное лучше будет если она и список будет рендерить

Не забывай про `<li>` 💀

2024-06-27 15:55 UTC, al-revenko commented on src/components/ui/Prices/Prices.tsx
> +      <PricesList>{pricesList}</PricesList>
и про `<ul>` 💀

2024-06-27 16:18 UTC, al-revenko commented on src/components/ui/Prices/Prices.tsx
> +    </li>
Из-за `<li>` походу вёрстка сломалась. Проверь адаптивность карт, исправь и кину апрув)

2024-06-27 16:37 UTC, al-revenko approved these changes

2024-06-27 18:07 UTC, kseniakap approved these changes

2024-06-27 18:07 UTC, kseniakap commented on src/components/ui/Prices/pricesData.ts
> +      'Начать',
"Начать" в макете нет)
![image](https://github.com/kseniakap/trafalgar/assets/119811424/c0cdb995-305d-4487-a0c1-136d0d03d39b)

2024-06-27 18:07 UTC, kseniakap commented on src/components/ui/Prices/Prices.tsx
> +        isPopular={price.isPopular}
Думаю, тут тоже деструктуризация здесь не будет лишней

2024-06-27 18:07 UTC, kseniakap commented on src/components/ui/Prices/pricesData.ts
> +    price: '$65',
Думаю, стоит оставить только цифры, а доллар написать в компоненте PricingCard
` <CrossOutPrice className="heading-1">${price}</CrossOutPrice>`

2024-06-28 10:30 UTC, Kalabass approved these changes

2024-06-28 11:14 UTC, G00syara commented
Потеряла `USD`, также перечёрнутая сумма не соответствует макету, надо ещё со стилизацией поиграться
![image](https://github.com/kseniakap/trafalgar/assets/95299564/2d69dd4c-8622-410e-8950-daa76f9ac0e1)
![image](https://github.com/kseniakap/trafalgar/assets/95299564/8daeff2b-182b-4d7b-9af7-a0aff034bbee)

2024-06-28 11:26 UTC, G00syara requested changes

2024-06-28 11:26 UTC, G00syara commented on src/components/ui/Card/PricingCard.tsx
> +      {isPopular ? (
Хорошая задумка, т.к. популярность штука изменчивая, можно сделать через логический оператор, чтобы лишний раз `null` не выводить
`isPopular && (<Badge> ....  </Badge>`

2024-06-28 11:26 UTC, G00syara commented on src/components/ui/Card/PricingCard.tsx
> +  background: #f2f4f8;
В `colors.ts`

2024-06-28 11:26 UTC, G00syara commented on src/components/ui/Card/PricingCard.tsx
>    border: 1px solid #dde1e6;
С остальными цветами аналогично

2024-06-28 11:26 UTC, G00syara commented on src/components/ui/Prices/pricesData.ts
> +    discount: '55',
Почему называется `discount`? А по факту это месячная цена? К тому же ты её не используешь, либо вырезать, либо значение скорректировать

2024-06-28 15:32 UTC, G00syara approved these changes

2024-06-28 15:32 UTC, merged