feat(TRA-23): подключил FactsBlock к home page
kseniakap/trafalgar pull request #25
Opened 2024-06-27 16:35 UTC by al-revenko

2024-06-27 16:59 UTC, aidagalimova approved these changes

2024-06-27 18:13 UTC, kseniakap approved these changes

2024-06-28 10:23 UTC, Kalabass approved these changes

2024-06-28 12:12 UTC, G00syara requested changes

2024-06-28 12:12 UTC, G00syara commented on src/components/ui/FactsBlock/FactsBlock.tsx
> +const FactsBlock: FC = () => {
Зачем если пропы не передаёшь?

2024-06-28 13:20 UTC, al-revenko commented on src/components/ui/FactsBlock/FactsBlock.tsx
> +const FactsBlock: FC = () => {
А почему нет? Нельзя явно указывать типы?

2024-06-28 13:39 UTC, G00syara approved these changes

2024-06-28 15:32 UTC, merged