Feature/tra 21
kseniakap/trafalgar pull request #29
Opened 2024-06-29 20:54 UTC by Kalabass

2024-06-30 05:20 UTC, al-revenko requested changes

2024-06-30 05:20 UTC, al-revenko commented on src/components/ui/StartUsingBlock/StartUsingForm.tsx
> +        <CustomButton type={ButtonType.Submit} text="Отправить" style={ButtonStyle.Contained}></CustomButton>
Кнопка "Отправить" должна очищать форму

2024-06-30 05:20 UTC, al-revenko commented on src/components/ui/StartUsingBlock/StartUsingForm.tsx
> +        ></FormControlLabel>
Походу `<FormControlLabel>` добавляет звёздочку и получается: "Согласен с политикой обработки данных *", в макете её нет, надо как-то убрать

2024-06-30 05:20 UTC, al-revenko commented on src/components/ui/StartUsingBlock/index.tsx
> +`;
Высота всего блока на десктопе 893px, а должна быть в районе ~1047px. На мобилке должна быть ~845px

2024-06-30 05:20 UTC, al-revenko commented on src/components/ui/StartUsingBlock/index.tsx
> +`;
Высота картинки на десктопе ~300px, должен быть 500px. На мобилке должна быть 279px

2024-06-30 05:20 UTC, al-revenko commented on src/components/ui/StartUsingBlock/index.tsx
> +`;
Форма должна быть не посередине блока, а впритык к нижнему отступу. Можно сделать отступ от верха блока в ~244px, на мобилке в ~151px (по макету) или просто прибить форму к нижнему отступу блока

2024-06-30 05:20 UTC, al-revenko commented on src/components/ui/StartUsingBlock/GroupMenuItems.tsx
Сделай функциональным список групп: галочка "выбрать всё" - должна отмечать все группы

2024-06-30 14:57 UTC, al-revenko requested changes

2024-06-30 14:57 UTC, al-revenko commented on src/components/ui/StartUsingBlock/StartUsingForm.tsx
> +        ></FormControlLabel>
Чекбокс не ресетится после отправки формы. Его, как одного из инпутов формы -  тоже надо очищать

2024-06-30 16:57 UTC, al-revenko approved these changes

2024-07-01 06:29 UTC, G00syara commented on src/components/ui/Select/index.tsx
> +  const [currentItem, setCurrentItem] = useState<string>('');
Можно не указывать тип у примитивных useState, реакт умный, сам понимает тип примитива

2024-07-01 10:38 UTC, sspopkov requested changes
![image](https://github.com/kseniakap/trafalgar/assets/52671474/3073c982-f344-4fc2-975c-b6bcda212743)
![image](https://github.com/kseniakap/trafalgar/assets/52671474/6a26ad87-5997-41e9-9bc9-d06fd9d996c6)
Ошибки в консоли

2024-07-01 20:04 UTC, sspopkov requested changes

2024-07-01 20:04 UTC, sspopkov commented on src/pages/home/index.tsx
> +      <a id="Главная">
Не надо создавать обёртки в виде ссылок с id, пропиши их внутри блоков

2024-07-01 20:04 UTC, sspopkov commented on src/pages/home/index.tsx
> +      <a id="О проекте">
Не используем русские слова для айдишников

2024-07-01 20:06 UTC, sspopkov requested changes
Используй лучше react-router-hash-link, react-scroll не работает с хэш

2024-07-02 11:41 UTC, sspopkov approved these changes

2024-07-02 11:41 UTC, merged